classdef Test_runner < OctaveTestCase
    % Runner behavior tests: targets, parameter filters, errors and
    % setUp/tearDown, exercised by invoking runoctests against scratch
    % test roots.  tearDown restores TEST_ROOT and removes the scratch
    % dirs and their path entries.
    properties
        scratchDirs = {}
        oldTestRoot = ''
        oldCi = ''
    end
    methods
        function testTargetsAndFilters(tc)
            root = tc.newRoot();
            tc.writeClass(root, 'Test_rparam1', {...
                'classdef Test_rparam1 < OctaveTestCase', ...
                '    methods', ...
                '        % @a = {"x", "y"}', ...
                '        % @b = {1, 2, 3}', ...
                '        function testTwo(tc, a, b)', ...
                '            tc.verifyTrue(ischar(a) || strcmp(class(a), ''string''));', ...
                '            tc.verifyTrue(isnumeric(b));', ...
                '            tc.recordPass();', ...
                '        end', ...
                '        function testNoArgs(tc)', ...
                '            tc.recordPass();', ...
                '        end', ...
                '    end', ...
                'end'});
            tc.withRoot(root);

            out = tc.runTarget('Test_rparam1/testTwo');
            tc.verifyTrue(tc.hasSubstr(out, '6 Passed'), ...
                'cartesian product runs all combinations');
            out = tc.runTarget('testTwo');
            tc.verifyTrue(tc.hasSubstr(out, '6 Passed'), ...
                'bare method name resolves to its class');
            out = tc.runTarget('Test_rparam1/testTwo("x",1)');
            tc.verifyTrue(tc.hasSubstr(out, '1 Passed'), ...
                'positional filter selects one combination');
            out = tc.runTarget('Test_rparam1/testTwo(,2)');
            tc.verifyTrue(tc.hasSubstr(out, '2 Passed'), ...
                'empty slot matches every annotated value');
            out = tc.runTarget('Test_rparam1/testTwo("z",1)');
            tc.verifyTrue(tc.hasSubstr(out, 'Errored'), ...
                'filter matching nothing reports an errored verdict');
        end

        function testTargetErrors(tc)
            root = tc.newRoot();
            tc.writeClass(root, 'Test_rparam2', {...
                'classdef Test_rparam2 < OctaveTestCase', ...
                '    methods', ...
                '        % @a = {"x"}', ...
                '        function testOne(tc, a)', ...
                '            tc.recordPass();', ...
                '        end', ...
                '        function testNoArgs(tc)', ...
                '            tc.recordPass();', ...
                '        end', ...
                '    end', ...
                'end'});
            tc.withRoot(root);

            threw = false;
            try
                tc.runTarget('Test_rparam2/testNoArgs(1)');
            catch e
                threw = strcmp(e.identifier, 'runoctests:paramsOnNoArgMethod');
            end
            tc.verifyTrue(threw, ...
                'parameters on a no-arg method throw runoctests:paramsOnNoArgMethod');

            threw = false;
            try
                tc.runTarget('Test_rparam2/testOne(1,2,3)');
            catch e
                threw = strcmp(e.identifier, 'runoctests:tooManyParams');
            end
            tc.verifyTrue(threw, ...
                'too many values throw runoctests:tooManyParams');
        end

        function testAmbiguousMethod(tc)
            root = tc.newRoot();
            tc.writeClass(root, 'Test_ramb1', {...
                'classdef Test_ramb1 < OctaveTestCase', ...
                '    methods', ...
                '        function testDup(tc)', ...
                '            tc.recordPass();', ...
                '        end', ...
                '    end', ...
                'end'});
            tc.writeClass(root, 'Test_ramb2', {...
                'classdef Test_ramb2 < OctaveTestCase', ...
                '    methods', ...
                '        function testDup(tc)', ...
                '            tc.recordPass();', ...
                '        end', ...
                '    end', ...
                'end'});
            tc.withRoot(root);

            threw = false;
            try
                tc.runTarget('testDup');
            catch e
                threw = strcmp(e.identifier, 'runoctests:ambiguousMethod') ...
                    && ~isempty(strfind(e.message, 'Test_ramb1')) ...
                    && ~isempty(strfind(e.message, 'Test_ramb2'));
            end
            tc.verifyTrue(threw, ...
                'ambiguous bare name throws runoctests:ambiguousMethod');
        end

        function testSetUpTearDown(tc)
            root = tc.newRoot();
            tc.writeClass(root, 'Test_rsdt', {...
                'classdef Test_rsdt < OctaveTestCase', ...
                '    methods', ...
                '        function setUp(tc)', ...
                '            if ~isempty(strfind(tc.CurrentTest, ''bad''))', ...
                '                error(''Test_rsdt:setupboom'', ''setUp boom for bad case'');', ...
                '            end', ...
                '        end', ...
                '        function tearDown(tc)', ...
                '            if ~isempty(strfind(tc.CurrentTest, ''testThrows''))', ...
                '                error(''Test_rsdt:tearAfterThrow'', ''tearDown ran after throw'');', ...
                '            end', ...
                '        end', ...
                '        function testA(tc)', ...
                '            tc.recordPass();', ...
                '        end', ...
                '        % @k = {"ok", "bad"}', ...
                '        function testParam(tc, k)', ...
                '            tc.recordPass();', ...
                '        end', ...
                '        function testThrows(tc)', ...
                '            error(''Test_rsdt:boom'', ''boom'');', ...
                '        end', ...
                '    end', ...
                'end'});
            tc.withRoot(root);

            out = tc.runTarget('Test_rsdt');
            tc.verifyTrue(tc.hasSubstr(out, '2 Passed, 0 Failed, 2 Errored'), ...
                'setUp/tearDown verdict counts');
            tc.verifyTrue(tc.hasSubstr(out, 'setUp boom for bad case'), ...
                'setUp runs per parameterized case and throws for the bad case');
            tc.verifyTrue(tc.hasSubstr(out, 'tearDown ran after throw'), ...
                'tearDown runs even after the body throws');
        end

        function tearDown(tc)
            if ~isempty(tc.oldTestRoot)
                setenv('TEST_ROOT', tc.oldTestRoot);
            else
                unsetenv('TEST_ROOT');
            end
            if ~isempty(tc.oldCi)
                setenv('CI', tc.oldCi);
            else
                unsetenv('CI');
            end
            for i = 1:numel(tc.scratchDirs)
                dir = tc.scratchDirs{i};
                p = path();
                if ~isempty(strfind([pathsep p pathsep], [pathsep dir pathsep]))
                    rmpath(dir);
                end
                try
                    rmdir(dir, 's');
                catch
                end
            end
            tc.scratchDirs = {};
        end
    end

    methods (Access = private)
        function dir = newRoot(tc)
            dir = fullfile(tempdir, sprintf('octest_run_%d', randi(1e6)));
            mkdir(dir);
            addpath(dir);
            tc.scratchDirs{end + 1} = dir;
        end

        function writeClass(tc, root, className, lines)
            fid = fopen(fullfile(root, [className '.m']), 'w');
            fprintf(fid, '%s\n', lines{:});
            fclose(fid);
        end

        function withRoot(tc, root)
            % nested runner invocations must not inherit CI: the runner
            % exits the process when CI is set and a verdict errored,
            % which would kill the selftest run
            tc.oldTestRoot = getenv('TEST_ROOT');
            setenv('TEST_ROOT', root);
            tc.oldCi = getenv('CI');
            setenv('CI', '');
        end

        function out = runTarget(tc, target)
            q = char(39);
            out = evalc(['runoctests(' q strrep(target, q, [q q]) q ')']);
        end

        function found = hasSubstr(tc, haystack, needle)
            found = ~isempty(strfind(haystack, needle));
        end
    end
end
