classdef Test_testparams < OctaveTestCase
    % Unit tests for testParams: annotation parsing, cartesian products
    % and signature validation, exercised on scratch classes written to
    % a temp directory.  tearDown removes the scratch dirs and their
    % path entries.
    properties
        scratchDirs = {}
    end
    methods
        function testCartesianProduct(tc)
            scratch = tc.writeScratch('Test_tp1', {...
                'classdef Test_tp1 < OctaveTestCase', ...
                '    methods', ...
                '        % @a = {"x", "y"}', ...
                '        % @b = {1, 2, 3}', ...
                '        function testTwo(tc, a, b)', ...
                '            tc.recordPass();', ...
                '        end', ...
                '        function testNoArgs(tc)', ...
                '            tc.recordPass();', ...
                '        end', ...
                '    end', ...
                'end'});
            [combos, argCount, argNames] = testParams(...
                fullfile(scratch, 'Test_tp1.m'), 'testTwo');
            tc.verifyEqual(argCount, 2);
            tc.verifyEqual(argNames, {'a', 'b'});
            tc.verifyNumElements(combos, 6);

            [combos0, n0] = testParams(...
                fullfile(scratch, 'Test_tp1.m'), 'testNoArgs');
            tc.verifyTrue(isempty(combos0) && n0 == 0, ...
                'no-arg method has no combos');
        end

        function testNonCellValueIsSingle(tc)
            scratch = tc.writeScratch('Test_tp2', {...
                'classdef Test_tp2 < OctaveTestCase', ...
                '    methods', ...
                '        % @n = 3', ...
                '        function testOne(tc, n)', ...
                '            tc.verifyEqual(n, 3);', ...
                '        end', ...
                '    end', ...
                'end'});
            [combos, argCount] = testParams(...
                fullfile(scratch, 'Test_tp2.m'), 'testOne');
            tc.verifyEqual(argCount, 1);
            tc.verifyNumElements(combos, 1);
            tc.verifyEqual(combos{1}{1}, 3);
        end

        function testSignatureMismatch(tc)
            scratch = tc.writeScratch('Test_tp3', {...
                'classdef Test_tp3 < OctaveTestCase', ...
                '    methods', ...
                '        % @wrongname = {"x"}', ...
                '        function testBad(tc, rightname)', ...
                '            tc.recordPass();', ...
                '        end', ...
                '    end', ...
                'end'});
            threw = false;
            try
                testParams(fullfile(scratch, 'Test_tp3.m'), 'testBad');
            catch e
                threw = strcmp(e.identifier, 'testParams:annotationName');
            end
            tc.verifyTrue(threw, ...
                'annotation/signature mismatch throws testParams:annotationName');
        end

        function tearDown(tc)
            for i = 1:numel(tc.scratchDirs)
                dir = tc.scratchDirs{i};
                p = path();
                if ~isempty(strfind([pathsep p pathsep], [pathsep dir pathsep]))
                    rmpath(dir);
                end
                try
                    rmdir(dir, 's');
                catch
                end
            end
            tc.scratchDirs = {};
        end
    end

    methods (Access = private)
        function dir = writeScratch(tc, className, lines)
            dir = fullfile(tempdir, sprintf('octest_tp_%d', randi(1e6)));
            mkdir(dir);
            fid = fopen(fullfile(dir, [className '.m']), 'w');
            fprintf(fid, '%s\n', lines{:});
            fclose(fid);
            addpath(dir);
            tc.scratchDirs{end + 1} = dir;
        end
    end
end
