name: CI

on:
  push:
  pull_request:

jobs:
  octave:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Octave
        run: |
          sudo apt-get update
          sudo apt-get install -y octave octave-statistics xvfb

      - name: Run selftests
        run: xvfb-run -a octave --no-gui --eval "warning('off', 'Octave:shadowed-function'); pkg load statistics; runoctests();"
        env:
          CI: 'true'
